BOT_TOKEN: 
  - ODY0OXXXXX # your_discord_bot_token
CHANNEL_ID: 
  - 12740XXXXXXXX # your_channel_id
MODE: ai_chat
OPENAI_API_KEY: sk-projXXXXXXXXXX # your_openai_api_key
SIMSIMI_LANG: en  # 
DELAY: 60
DEL_AFTER: false
REPLY: true
REPOST_LAST_CHAT: 100